### ISSUE TITLE
the name is a bit confusing

### ISSUE THREAD

**Issue by glorysdj** [digitalscream/ipex-llm-fastchat-docker#1]
Hi
It's really great, thanks for your great work! The name is a bit confusing to me. It seems that this Docker is leveraging ipex-llm, so would it be more appropriate to name the repo and image as ipex-llm-fastchat-docker?

**Comment by digitalscream** [comment]
That's a fair point - wasn't particularly attached to the name, and since GitHub happily redirects from the old slug...done :)
